name: Java CI with Maven

on:
  push:
    branches: [ "Akira_GithubActions" ]
  pull_request:
    branches: [ "Akira_GithubActions" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: cab302_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Give Maven Wrapper permission
        run: chmod +x mvnw

      - name: Build and Test with Maven Wrapper
        run: ./mvnw -B verify
