name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write #give the bot permission to write

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: cab302_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Give Maven Wrapper permission
        run: chmod +x mvnw

      - name: Build and Test
        env:
          DB_URL: jdbc:mysql://127.0.0.1:3306/cab302_test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
          DB_USER: root
          DB_PASS: root
        run: mvn -B verify


      # ----------------------------
      # 📘 Javadoc Generation Section
      # ----------------------------
      - name: Generate Javadoc
        run: |
          ./mvnw -B clean javadoc:javadoc \
            -Dmaven.javadoc.failOnError=false \
            -Dmaven.javadoc.skip=false \
            -Dsourcepath=src/main/java \
            -Dencoding=UTF-8


      - name: Verify Javadoc Output
        run: |
           echo "📂 Generated files:"
           ls -R target/reports/apidocs || echo "⚠️ No Javadoc generated!"

      - name: Upload Javadoc artifact
        uses: actions/upload-artifact@v4
        with:
          name: javadoc
          path: target/reports/apidocs/
          retention-days: 30 # 30 days is enough for sure


  #jb
  ui-student-quiz-tests:
    name: UI Tests (Student Quiz taking)
    runs-on: ubuntu-latest
    needs: build
    if: ${{ always() }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Upload surefire reports (ui - student quiz)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-ui-student-quiz
          path: |
            **/target/surefire-reports/*
            **/target/failsafe-reports/*