name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: cab302_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Give Maven Wrapper permission
        run: chmod +x mvnw

      - name: Build and Test
        env:
          DB_URL: jdbc:mysql://localhost:3306/cab302_test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
          DB_USER: root
          DB_PASS: root
        run: ./mvnw -B verify

#jb
  ui-student-quiz-tests:
    name: UI Tests (Student Quiz taking)
    runs-on: ubuntu-latest
    needs: build
    if: ${{ always() }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

#virtual X server
      - name: Install Xvfb & Linux deps for JavaFX
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgtk-3-0 libnss3 libasound2 libgl1-mesa-dri

      - name: Enable UI tests (remove surefire excludes block in pom.xml)
        run: |
          # Remove lines between <excludes> and </excludes> (only for this job)
          sed -i '/<excludes>/,/<\/excludes>/d' pom.xml
          echo "After patching pom.xml:"
          grep -n "<excludes>" -n pom.xml || true

      - name: Run ONLY StudentTakeQuizControllerTest (headless)
        env:
          DISPLAY: ":99"
          MAVEN_OPTS: "-Dtestfx.headless=true -Djava.awt.headless=true -Dglass.platform=Monocle -Dmonocle.platform=Headless -Dprism.order=sw -Dprism.text=t2k"
        run: |
          # Start a virtual X display
          Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          sleep 2
          # Run only the Student Quiz taking UI test
          mvn -B -DfailIfNoTests=false -Dtest=com.example.cab302a1.ui.StudentTakeQuizControllerTest test

      - name: Upload surefire reports (ui - student quiz)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-ui-student-quiz
          path: |
            **/target/surefire-reports/*
            **/target/failsafe-reports/*